package com.isaquesoft.despesas.utils

import android.content.Context
import android.graphics.drawable.Drawable
import com.isaquesoft.despesas.R

class IconsCategory {

    fun listIcons(context: Context): MutableList<Drawable> {
        val drawableList = mutableListOf<Drawable>()
        drawableList.add(context.getDrawable(R.drawable.aviao)!!)
        drawableList.add(context.getDrawable(R.drawable.bike)!!)
        drawableList.add(context.getDrawable(R.drawable.bus)!!)
        drawableList.add(context.getDrawable(R.drawable.cadeado)!!)
        drawableList.add(context.getDrawable(R.drawable.camera)!!)
        drawableList.add(context.getDrawable(R.drawable.car)!!)
        drawableList.add(context.getDrawable(R.drawable.cardn)!!)
        drawableList.add(context.getDrawable(R.drawable.farmacia)!!)
        drawableList.add(context.getDrawable(R.drawable.foneouvido)!!)
        drawableList.add(context.getDrawable(R.drawable.impressora)!!)
        drawableList.add(context.getDrawable(R.drawable.moto)!!)
        drawableList.add(context.getDrawable(R.drawable.piscina)!!)
        drawableList.add(context.getDrawable(R.drawable.roupas)!!)
        drawableList.add(context.getDrawable(R.drawable.viagem)!!)
        drawableList.add(context.getDrawable(R.drawable.cartao)!!)
        drawableList.add(context.getDrawable(R.drawable.saude)!!)
        drawableList.add(context.getDrawable(R.drawable.filmes)!!)
        drawableList.add(context.getDrawable(R.drawable.outros)!!)
        drawableList.add(context.getDrawable(R.drawable.comidaebebida)!!)
        drawableList.add(context.getDrawable(R.drawable.transporte)!!)
        drawableList.add(context.getDrawable(R.drawable.eletronicos)!!)
        drawableList.add(context.getDrawable(R.drawable.educacao)!!)
        drawableList.add(context.getDrawable(R.drawable.entretenimento)!!)
        drawableList.add(context.getDrawable(R.drawable.batimentos)!!)
        drawableList.add(context.getDrawable(R.drawable.bebe)!!)
        drawableList.add(context.getDrawable(R.drawable.beblia)!!)
        drawableList.add(context.getDrawable(R.drawable.bola)!!)
        drawableList.add(context.getDrawable(R.drawable.bolo)!!)
        drawableList.add(context.getDrawable(R.drawable.carrinhobebe)!!)
        drawableList.add(context.getDrawable(R.drawable.carrinhobebe2)!!)
        drawableList.add(context.getDrawable(R.drawable.carrinhocompras)!!)
        drawableList.add(context.getDrawable(R.drawable.casa)!!)
        drawableList.add(context.getDrawable(R.drawable.cesta)!!)
        drawableList.add(context.getDrawable(R.drawable.cifrao)!!)
        drawableList.add(context.getDrawable(R.drawable.comidaprato)!!)
        drawableList.add(context.getDrawable(R.drawable.dog)!!)
        drawableList.add(context.getDrawable(R.drawable.gato)!!)
        drawableList.add(context.getDrawable(R.drawable.gps)!!)
        drawableList.add(context.getDrawable(R.drawable.livro)!!)
        drawableList.add(context.getDrawable(R.drawable.navio)!!)
        drawableList.add(context.getDrawable(R.drawable.smartwatch)!!)
        drawableList.add(context.getDrawable(R.drawable.trofeu)!!)
        drawableList.add(context.getDrawable(R.drawable.violao)!!)
        drawableList.add(context.getDrawable(R.drawable.banco)!!)
        drawableList.add(context.getDrawable(R.drawable.bolsa)!!)
        drawableList.add(context.getDrawable(R.drawable.cerveja)!!)
        drawableList.add(context.getDrawable(R.drawable.chave)!!)
        drawableList.add(context.getDrawable(R.drawable.controle)!!)
        drawableList.add(context.getDrawable(R.drawable.corrida)!!)
        drawableList.add(context.getDrawable(R.drawable.ferramentas)!!)
        drawableList.add(context.getDrawable(R.drawable.futebol)!!)
        drawableList.add(context.getDrawable(R.drawable.galao)!!)
        drawableList.add(context.getDrawable(R.drawable.gasolina)!!)
        drawableList.add(context.getDrawable(R.drawable.gasolina1)!!)
        drawableList.add(context.getDrawable(R.drawable.igreja)!!)
        drawableList.add(context.getDrawable(R.drawable.igreja1)!!)
        drawableList.add(context.getDrawable(R.drawable.medalha)!!)
        drawableList.add(context.getDrawable(R.drawable.olho)!!)
        drawableList.add(context.getDrawable(R.drawable.peso)!!)
        drawableList.add(context.getDrawable(R.drawable.pessoa)!!)
        drawableList.add(context.getDrawable(R.drawable.skate)!!)
        drawableList.add(context.getDrawable(R.drawable.sopa)!!)
        drawableList.add(context.getDrawable(R.drawable.talher)!!)
        drawableList.add(context.getDrawable(R.drawable.taxi)!!)
        drawableList.add(context.getDrawable(R.drawable.pipoca)!!)
        drawableList.add(context.getDrawable(R.drawable.pizza)!!)
        return drawableList
    }
}
